[build]
target = "x86_64-unknown-none"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-none]
rustflags = ["-C", "relocation-model=static", "-C", "code-model=large"]
